events {}

http {

    upstream bus_service {
        server app1:80;
    }

    upstream movie_service {
        server app2:80;
    }

    upstream flight_service {
        server app3:80;
    }

    server {

        listen 80;

        location /bus/ {
            proxy_pass http://bus_service/;
        }

        location /movie/ {
            proxy_pass http://movie_service/;
        }

        location /flight/ {
            proxy_pass http://flight_service/;
        }
    }
}
