events {}

http {

    resolver 127.0.0.11 valid=30s;

    upstream bus_service {
        server app1:80;
    }

    upstream movie_service {
        server app2:80;
    }

    upstream flight_service {
        server app3:80;
    }

    server {

        listen 80;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        location /bus/ {

            proxy_pass http://bus_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /movie/ {

            proxy_pass http://movie_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /flight/ {

            proxy_pass http://flight_service/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
